const express = require('express')
const { THIS } = require('./method/LS_ZZE4NDI2MZIWNTQ')
const { ROUTER_LS_YTE4MTK0NDQZMTY } = require('./route/ROUTER_LS_YTE4MTK0NDQZMTY')
const { REGISTER_LS_ADE4MTK0NZYYNTM } = require('./setup/REGISTER_LS_ADE4MTK0NZYYNTM')



REGISTER_LS_ADE4MTK0NZYYNTM()

const BLOGER = express()

const NUMBER = THIS.CURRENT.GET_CONFIG().NUMBER

BLOGER.use(THIS.CONFIG_DEFAULT().NORMAL.RIGHT_SLASH_SYMBOL, THIS.MIDDLE.WATCH, ROUTER_LS_YTE4MTK0NDQZMTY)

BLOGER.listen(NUMBER, () => {
    THIS.EX.NOTE(THIS.CONFIG_DEFAULT().MESSAGE.CURRENT_LISTEN + NUMBER)
})



