const { LS_EDE4MJKXMDGZNJE } = require("./include/LS_EDE4MJKXMDGZNJE")
const { LS_ETM1NJK1NJG0NTE } = require("./include/LS_ETM1NJK1NJG0NTE")

const LS_ZDE4MJC5NDC0MDI = () => {
    return {
        STATIC: LS_EDE4MJKXMDGZNJE(),
        CURRENT: LS_ETM1NJK1NJG0NTE(),
    }
}

module.exports.LS_ZDE4MJC5NDC0MDI = LS_ZDE4MJC5NDC0MDI