const { LS_ATE5NDI4NTU3NJE } = require("./include/LS_ATE5NDI4NTU3NJE")
const { LS_BJMWNDM4MJA2OTU } = require("./include/LS_BJMWNDM4MJA2OTU")
const { LS_CZIWMZY0MTA3MZC } = require("./include/LS_CZIWMZY0MTA3MZC")
const { LS_EDI1NTA4MZE4OTE } = require("./include/LS_EDI1NTA4MZE4OTE")
const { LS_ETE5MJIWMJY0NTE } = require("./include/LS_ETE5MJIWMJY0NTE")

const LS_EJE4MJGZNTKWMDK = () => {

    const { LS_ADE4MJGYMZU4MTG } = require("./include/LS_ADE4MJGYMZU4MTG")
    const { LS_AJE4MJG2OTQ1MTM } = require("./include/LS_AJE4MJG2OTQ1MTM")
    const { LS_ATE4MJG3ODI1MJE } = require("./include/LS_ATE4MJG3ODI1MJE")
    const { LS_AZE4MJG4OTEYODI } = require("./include/LS_AZE4MJG4OTEYODI")
    const { LS_BZE4MJG0MDK3MJI } = require("./include/LS_BZE4MJG0MDK3MJI")
    const { LS_CDE4MJGYNTK4MJU } = require("./include/LS_CDE4MJGYNTK4MJU")
    const { LS_EDE4MJG1MDU3ODY } = require("./include/LS_EDE4MJG1MDU3ODY")
    const { LS_ZZE4NDY4MZI1OTU } = require("./include/LS_ZZE4NDY4MZI1OTU")

    return {
        NORMAL: LS_CDE4MJGYNTK4MJU(),
        MESSAGE: LS_ADE4MJGYMZU4MTG(),
        NUMBER: LS_EDE4MJG1MDU3ODY(),
        ATTRIBUTE: LS_BZE4MJG0MDK3MJI(),
        ATTRIBUTE_VALUE: LS_AZE4MJG4OTEYODI(),
        TAG: LS_AJE4MJG2OTQ1MTM(),
        REPLACE: LS_ATE4MJG3ODI1MJE(),
        VARIBLE: LS_ZZE4NDY4MZI1OTU(),
        PAPER: LS_ATE5NDI4NTU3NJE(),
        CONVERT_METHOD:LS_CZIWMZY0MTA3MZC(),
        ELEMENT: LS_EDI1NTA4MZE4OTE(),
        QUERY: LS_BJMWNDM4MJA2OTU(),
    }
}

module.exports.LS_EJE4MJGZNTKWMDK = LS_EJE4MJGZNTKWMDK

