const LS_CDE4MJGYNTK4MJU = () => {
    return {
        NUMBER_ONE_MINUS: -1,
        NUMBER_ZERO: 0,
        NUMBER_ONE: 1,
        NUMBER_TWO: 2,
        NUMBER_THREE: 3,
        NUMBER_FOUR: 4,
        NUMBER_FIVE: 5,
        SEMICOLON_SYMBOL: ";",
        UNDERLINE_SYMBOL: "_",
        DOT_SYMBOL: ".",
        DOUBLE_DOT_SYMBOL: "..",
        NGA_SYMBOL: "~",
        RIGHT_SLASH_SYMBOL: "/",
        DOUBLE_RIGHT_SLASH_SYMBOL: "//",
        THANG_SYMBOL: "#",
        LEFT_SLASH_SYMBOL: "\\",
        LINE_SYMBOL: "|",
        EQUAL_SYMBOL: "=",
        LEFT_BRACKET_SYMBOL: "(",
        RIGHT_BRACKET_SYMBOL: ")",
        LEFT_SARO_SYMBOL: "<",
        RIGHT_SARO_SYMBOL: ">",
        LEFT_QUERA_SYMBOL: "[",
        RIHGT_QUERA_SYMBOL: "]",
        C_CHAM_SYMBOL: ":",
        COMMA_SYMBOL: ",",
        COOKIE_EXPIRES: "expires=",
        RANDOM_CHARACTOR: "qwertyuioplkjhgfdsazxcvbnm0123456789",
        COOKIE_PATH: "path=",
        DASH_SYMBOL: "-",
        STRING_EMPTY: "",
        NHAY_SYMBOL: "\"",
        SINGLE_NHAY_SYMBOL: "'",
        NHAY_CHAR_SYMBOL: "`",
        NHAY_SYMBOL_SPECIAL: "\"",
        BREAK_LINE_SYMBOL: "\n",
        REQUEST_SYMBOL: "?",
        AND_SYMBOL: "&",
        SPACE: " ",
        FALSE: false,
        TRUE: true,
        ARRAY_EMPTY: [],
        OBJECT_EMPTY: {},
    }
}

module.exports.LS_CDE4MJGYNTK4MJU = LS_CDE4MJGYNTK4MJU