const { LS_BZE5NDQWNZQXMZQ } = require("./include/LS_BZE5NDQWNZQXMZQ")
const { LS_CJIWMDC1MDYZMTY } = require("./include/LS_CJIWMDC1MDYZMTY")
const { LS_ZZIWMZCZMJUZNZQ } = require("./include/LS_ZZIWMZCZMJUZNZQ")

const LS_EDE5NDM5OTY3NTA = () => {
    return {
        MEMORY: LS_BZE5NDQWNZQXMZQ(),
        PATH: LS_ZZIWMZCZMJUZNZQ(),
        MONGODB: LS_CJIWMDC1MDYZMTY()
    }
}

module.exports.LS_EDE5NDM5OTY3NTA = LS_EDE5NDM5OTY3NTA