const LS_BZE5NDQWNZQXMZQ = () => {
    return {
        COLLECTION: {
            COLLECTION_ADDED: "COLLECTION_ADDED_LS_ZDE4MJUXMJQ2MJM",
            LAST_UPDATE_MEMORY: "LAST_UPDATE_MEMORY_LS_CDE4MJYYMZC3OTC",
            AUTHOR: "AUTHOR_LS_ZTE4MJUXNDI5MJU",
            CONTENT_DETAIL: "CONTENT_DETAIL_LS_ATE4MJUXODQYMZC",
            CONTENT_INFO: "CONTENT_INFO_LS_DJE4MJUYMZYWNJE",
            CATEGORY: "CATEGORY_LS_AJE5NTI5MZU4NJC",
            BOOK: "BOOKS_LS_CZE5NTI5NJG5NDG",
            REGISTER_JOBS: "REGISTER_JOBS_LS_BZIXMJA4MDC4NZI",
            NO_MAIN_OR_THEME: "NO_MAIN_OR_THEME_LS_CTI1MTKXNDC4MJK"
        },
        PROPERTIES: {
            BEST_CONTENT_ON_PAGES: "BEST_CONTENT_ON_PAGES_",
            BEST_CONTENT_ON_CATEGORY: "_CATEGORY_PAGES_",
            BEST_CONTENT_ON_BOOK: "_BOOK_PAGES_",
            BEST_CONTENT_ON_AUTHOR: "AUTHOR_PAGES_",
            HOT_CONTENT: "HOT_CONTENT",
            SAME_CONTENT: "SAME_CONTENT_",
            AUTHOR: "AUTHOR_",
            CATEGORY: "CATEGORY_",
            BOOK: "BOOK_",
            CONTENT_DETAIL: "CONTENT_DETAIL_",
            CONTENT_INFO: "CONTENT_INFO_",
            COUNT_CONTENT_INFO: "COUNT_CONTENT_INFO",
            COUNT_CONTENT_AUTHOR: "COUNT_CONTENT_AUTHOR_",
            COUNT_CONTENT_CATEGORY: "COUNT_CONTENT_CATEGORY_",
            COUNT_CONTENT_BOOK: "COUNT_CONTENT_BOOK_",

            INTRODUCE_DETAIL_INFO: "INTRODUCE_DETAIL_INFO",
            INTRODUCE: "INTRODUCE_",

            DUMPART_INFO: "DUMPART_INFO",
            DUMPART_ITEMS: "DUMPART_INFO_ITEMS_",
            DUMPART_DETAIL_ITEMS: "DUMPART_DETAIL_ITEMS_",

            OTHER_FOOTER_INFO: "OTHER_FOOTER_INFO",
            CATEGORY_PIN: "CATEGORY_PIN",
            HEADER_CATEGORY: "HEADER_CATEGORY"
           
        },
        CONFIG: {
            MINUTE_UPDATE_MEMORY: 5
        }
    }
}

module.exports.LS_BZE5NDQWNZQXMZQ = LS_BZE5NDQWNZQXMZQ