const { FIX_LATE_LS_CDM2NDI0MTY0NZQ } = require("../component/content/exeptions/FIX_LATE_LS_CDM2NDI0MTY0NZQ")
const { NOT_FOUND_LS_ATMZMDCZNTA4NZU } = require("../component/content/exeptions/NOT_FOUND_LS_ATMZMDCZNTA4NZU")
const { AUTHOR_LS_YTI3NJCYMJI1NJG } = require("../content/AUTHOR_LS_YTI3NJCYMJI1NJG")
const { BOOK_LS_ADMZMDCXMJG3MDY } = require("../content/BOOK_LS_ADMZMDCXMJG3MDY")
const { CATEGORY_LS_BDI2MDK2ODU3MTA } = require("../content/CATEGORY_LS_BDI2MDK2ODU3MTA")
const { HELP_LS_DTI2MTAYNDUXODC } = require("../content/HELP_LS_DTI2MTAYNDUXODC")
const { HOME_LS_DZE4MTKZOTIYMDU } = require("../content/HOME_LS_DZE4MTKZOTIYMDU")
const { READ_LS_ETIYMDAYOTK3OTA } = require("../content/READ_LS_ETIYMDAYOTK3OTA")

const REGISTER_LS_ADE4MTK0NZYYNTM = () => {
    HOME_LS_DZE4MTKZOTIYMDU()
    READ_LS_ETIYMDAYOTK3OTA()
    HELP_LS_DTI2MTAYNDUXODC()
    CATEGORY_LS_BDI2MDK2ODU3MTA()
    AUTHOR_LS_YTI3NJCYMJI1NJG()
    BOOK_LS_ADMZMDCXMJG3MDY()


    //EXCEPTIONS
    FIX_LATE_LS_CDM2NDI0MTY0NZQ()
    NOT_FOUND_LS_ATMZMDCZNTA4NZU()
}


module.exports.REGISTER_LS_ADE4MTK0NZYYNTM = REGISTER_LS_ADE4MTK0NZYYNTM